[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Audulus-Canvas"
authors = [{name = "Mark Alan Boyd", email = "markalanboyd@gmail.com"}]
dynamic = ["version", "description"]